### ISSUE TITLE
請求先アカウント変更する

### ISSUE THREAD

**Issue by springaki** [shinosakarb/tebukuro-client#44]
@murajun1978 さんのアカウントの無料期間が終わるので他の人に請求先移して支払いを回避する

まずは @ytorii さんに移す

**Comment by ytorii** [comment]
Issue moved to [shinosakarb/tebukuro #246](https://github.com/shinosakarb/tebukuro/issues/246) via [**ZenHub**](https://www.zenhub.com/)
